### ISSUE TITLE
Blank & duplicate SSID entries

### ISSUE THREAD

**Issue by t16n** [balena-io/wifi-connect#265]
In the network list I can see multiple entries for the same SSIDs. Also I see empty entries.

https://github.com/balena-io/wifi-connect/pull/61
and 
https://github.com/balena-io/wifi-connect/pull/202

tried to fix it, but i think the issue still remains.

**Comment by majorz** [comment]
@t16n right, I believe the code has changed from the time those issues were created. Probably the easiest way for fixing is filtering duplicated ssid members in the JavaScript here: https://github.com/balena-io/wifi-connect/blob/6547a4a77c76d0ec903033f44a177f312c2831fe/ui/js/index.js#L21

I will handle those cases when I get back to transitioning the project to the new NetworkManager Rust library I have been working on, but I am not sure when I will be able to dedicate the time for this because of the higher priorities with some other projects we have.

**Comment by astekardis** [comment]
Has there been any progress on this? I'm trying to use wifi-connect and am seeing duplicate networks appear in the SSID list (none of the duplicate networks are the one that I need to connect to).
<img width="910" alt="Screen Shot 2019-11-05 at 11 10 00 AM" src="https://user-images.githubusercontent.com/56287775/68237005-279bcd00-ffbb-11e9-84ea-26c57d57c090.png">

**Comment by HughWarrington** [comment]
This affects me too. Any update?

**Comment by majorz** [comment]
Both of those issues are now fixed in v4.4.3.
