### ISSUE TITLE
Remove wifi connections

### ISSUE THREAD

**Issue by t16n** [balena-io/wifi-connect#270]
I've configured multiple Network connections and they all got remembered. Wich is great! 
Is there currently a way to delete all the connections that have been created for the NetworkManager/system-connections.
I know i could do it manually by connection into the host system and deleting all the connections. but is there an other way to do it programmatically out of the container?
How would i do it over DBUS?

**Comment by majorz** [comment]
If we are talking about a connection to the same network, WiFi Connect will delete it automatically when new password is entered. It will not touch other existing connections.

Usually in production environment you do not have to enable many networking connections, and it is not a problem to keep old connection profiles. Those can be deleted with nmcli from a host OS terminal if necessary.

For applications where you expect to have many connections and you would like to clean up them regularly then you need to use the NetworkManager D-Bus API indeed. I recommend using the python-networkmanager library if you are using Python. You may check the available documentation on our website for extra information: https://www.balena.io/docs/reference/OS/network/2.x/#changing-the-network-at-runtime

**Comment by t16n** [comment]
If anyone else is interested this is how you can delete all connections for example:

`#!/usr/bin/env python
import dbus, uuid

bus = dbus.SystemBus()
proxy = bus.get_object("org.freedesktop.NetworkManager", "/org/freedesktop/NetworkManager/Settings")
settings = dbus.Interface(proxy, "org.freedesktop.NetworkManager.Settings")

connection_paths = settings.ListConnections()

for path in connection_paths:
       con_proxy = bus.get_object("org.freedesktop.NetworkManager", path)
       settings_connection = dbus.Interface(con_proxy, "org.freedesktop.NetworkManager.Settings.Connection")
       config = settings_connection.GetSettings()
       settings_connection.Delete()
`

**Comment by maggie0002** [comment]
For reference another Python solution here which I found to work slightly better. 

https://github.com/OpenAgricultureFoundation/python-wifi-connect/blob/master/nm_scripts/delete_all_wifi_connections.py

**Comment by maggie0002** [comment]
And an adapted version for reference: https://github.com/maggie0002/unofficial-balena-flask-api

**Comment by jense-arntz** [comment]
Hi everyone,

I also want to remove all wifi connection programmatically in the container. I was able to delete the specific connection with the following commands.
------------------
nmcli connection down id "ssid" || true
nmcli connection delete id "ssid" || true
------------------
But what I really want to is delete all wifi connections in my django container. Otherwise, is it possible to run those commands on hostOS in the container? 
Here are all settings for django service in docker-compose.yml file
------------------
django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    network_mode: "host"
    privileged: true
    volumes:
      - ./:/app/
      - /run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
    depends_on:
      - db
    restart: always
#    ports:
#      - "8000:8000"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    cap_add:
      - NET_ADMIN
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS="unix:path=/host/run/dbus/system_bus_socket"
------------------

To use nmcli command in the container, I installed Network-manager by the following command.
>apt-get update && apt-get install -y network-manager && systemctl mask NetworkManager.service
And I run executed the following command in the container

 nmcli connection down id "TP-LINK-REAL3D" || true
 nmcli connection delete id "TP-LINK-REAL3D" || true

But I got the following error.

![image](https://user-images.githubusercontent.com/17856450/105108021-50db4700-5af4-11eb-8639-c3b5e37103d2.png)
How can I solve this error?
Thanks in advance.

Anatoli

**Comment by jense-arntz** [comment]
> If anyone else is interested this is how you can delete all connections for example:
> 
> ```
> #!/usr/bin/env python
> import dbus, uuid
> 
> bus = dbus.SystemBus()
> proxy = bus.get_object("org.freedesktop.NetworkManager", "/org/freedesktop/NetworkManager/Settings")
> settings = dbus.Interface(proxy, "org.freedesktop.NetworkManager.Settings")
> 
> connection_paths = settings.ListConnections()
> 
> for path in connection_paths:
>        con_proxy = bus.get_object("org.freedesktop.NetworkManager", path)
>        settings_connection = dbus.Interface(con_proxy, "org.freedesktop.NetworkManager.Settings.Connection")
>        config = settings_connection.GetSettings()
>        settings_connection.Delete()
> ```

Hi,
Can I execute this script in the container? Is that a way to remove all wifi-connection programmatically in the container?
