### ISSUE TITLE
Installing on Raspbian Stretch Lite  - Raspberry Pi Zero W - Locks up system

### ISSUE THREAD

**Issue by scottrpaterson** [balena-io/wifi-connect#282]
Trying to install on Raspberry Pi Zero W running Raspbian Stretch Lite. After running:

bash <(curl -L https://github.com/balena-io/wifi-connect/raw/master/scripts/raspbian-install.sh)

It lock up at this point:

![Capture](https://user-images.githubusercontent.com/11578353/55513169-536c6400-5622-11e9-8f61-172114c49d42.PNG)

I can't exit the script running. Even rebooting the Raspberry Pi does not allow me to connect at all or ping it, the only option it to reflash the memory card image.

**Comment by majorz** [comment]
@scottrpaterson currently it is a bit tricky to install WiFi Connect on a RPi Zero W. The problem is that once you start installing WiFi Connect it will drop the WiFi connection during the installation. Since the installer does not add WiFi Connect as a startup service currently, after reboot you will not have wireless connectivity.

I have a few ideas how to improve this experience, but until this is implemented the easiest way is to install it with a keyboard and monitor directly attached to it, or over Ethernet with an USB adapter like this one: https://shop.pimoroni.com/products/three-port-usb-hub-with-ethernet-and-microb-connector

**Comment by scottrpaterson** [comment]
@majorz,

Thanks for the answer. That definitely explains what happened. Please consider add this to your docs. You can close this issue.
